package com.verycars.model;
// Generated 19 déc. 2021 à 20:06:44 by Hibernate Tools 5.4.14.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Commande generated by hbm2java
 */
@Entity
public class Commande implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="id_commande")
	private Integer id;
	private String utilisateur;
	private String voiture;
	private int quantite;
	private String prix;
	private String description;
	private String image;
	private String nom;

	public Commande() {
	}

	public Commande(String utilisateur, String voiture, int quantite) {
		this.utilisateur = utilisateur;
		this.voiture = voiture;
		this.quantite = quantite;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(String utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getVoiture() {
		return this.voiture;
	}

	public void setVoiture(String voiture) {
		this.voiture = voiture;
	}

	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	public String getPrix() {
		return prix;
	}

	public void setPrix(String prix) {
		this.prix = prix;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
