package com.verycars.model;
// Generated 19 déc. 2021 à 20:06:44 by Hibernate Tools 5.4.14.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Voiture generated by hbm2java
 */
@Entity
public class Voiture implements java.io.Serializable {
	@Id
	private Integer idVoiture;
	private String type;
	private String image;
	private String nom;
	private String prix;
	private String description;
	private Integer stock;

	public Voiture() {
	}

	public Voiture(String type, String image, String nom, String prix, String description, Integer stock) {
		this.type = type;
		this.image = image;
		this.nom = nom;
		this.prix = prix;
		this.description = description;
		this.stock = stock;
	}

	public Integer getId() {
		return this.idVoiture;
	}

	public void setId(Integer id) {
		this.idVoiture = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrix() {
		return this.prix;
	}

	public void setPrix(String prix) {
		this.prix = prix;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

}
